### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by yehezkieldio** [FutureDeveloperZ/web#1]
### ⇁ Performance
- [x] Better CSS Reset. (Normalize.css)
- [ ] Clean code.

### ⇁ Features
- [x] Animations on Scroll. (AOS)
- [ ] Page Pre-loader.
- [ ] Font & Colors Upgrade.
- [ ] Rework Command list & Support.
- [ ] Desktop friendly design.
